name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Test
        run: cargo test --all-targets
      - name: Build release binary
        run: cargo build --release
